-- Run from the routing folder:
-- sqlplus -L "DEVELOPER_READ_ONLY@//enmtdbprd.az.3pc.att.com:1521/enmt_22464_prd.db.att.com" "@check_psap_mapping_simple.sql"

WHENEVER SQLERROR EXIT SQL.SQLCODE

SET ECHO OFF
SET VERIFY OFF
SET FEEDBACK ON
SET HEADING ON
SET PAGESIZE 100
SET LINESIZE 32767
SET TRIMSPOOL ON
SET SQLBLANKLINES ON
SET TERMOUT ON
SET MARKUP CSV ON DELIMITER , QUOTE ON

SPOOL psap_id_mapping_summary.csv

WITH call_sample AS (
    SELECT PSAP_ID, FCC_PSAP_ID, PSAP_NAME
    FROM E911.E911_PSAPSIM_CALL_DETAILS_LTE
    WHERE PSAP_ID IS NOT NULL
       OR FCC_PSAP_ID IS NOT NULL
       OR PSAP_NAME IS NOT NULL
    FETCH FIRST 10000 ROWS ONLY
),
calls AS (
    SELECT
        REGEXP_REPLACE(UPPER(TRIM(CAST(PSAP_ID AS VARCHAR2(100)))), '[.]0$', '') AS PSAP_ID_NORM,
        REGEXP_REPLACE(UPPER(TRIM(CAST(FCC_PSAP_ID AS VARCHAR2(100)))), '[.]0$', '') AS FCC_ID_NORM,
        REGEXP_REPLACE(UPPER(TRIM(CAST(PSAP_NAME AS VARCHAR2(500)))), '[^A-Z0-9]', '') AS PSAP_NAME_NORM
    FROM call_sample
),
legacy_fcc AS (
    SELECT DISTINCT REGEXP_REPLACE(UPPER(TRIM(CAST(FCC_PSAP_ID AS VARCHAR2(100)))), '[.]0$', '') AS ID_VALUE
    FROM E911.E911_PSAP_BOUNDARIES
    WHERE FCC_PSAP_ID IS NOT NULL
),
legacy_nena AS (
    SELECT DISTINCT REGEXP_REPLACE(UPPER(TRIM(CAST(NENA_ID AS VARCHAR2(100)))), '[.]0$', '') AS ID_VALUE
    FROM E911.E911_PSAP_BOUNDARIES
    WHERE NENA_ID IS NOT NULL
),
fcc_table_id AS (
    SELECT DISTINCT REGEXP_REPLACE(UPPER(TRIM(CAST(FCC_PSAP_ID AS VARCHAR2(100)))), '[.]0$', '') AS ID_VALUE
    FROM E911.E911_PSAP_BOUNDARIES_FCC
    WHERE FCC_PSAP_ID IS NOT NULL
),
fcc_json_id AS (
    SELECT DISTINCT REGEXP_REPLACE(
        UPPER(TRIM(JSON_VALUE(PROPERTIES, '$.properties.FCC_ID'
            RETURNING VARCHAR2(100) NULL ON ERROR))), '[.]0$', '') AS ID_VALUE
    FROM E911.E911_PSAP_BOUNDARIES_FCC
),
fcc_json_name AS (
    SELECT DISTINCT REGEXP_REPLACE(
        UPPER(TRIM(JSON_VALUE(PROPERTIES, '$.properties.PSAP_NAME'
            RETURNING VARCHAR2(500) NULL ON ERROR))), '[^A-Z0-9]', '') AS ID_VALUE
    FROM E911.E911_PSAP_BOUNDARIES_FCC
),
results AS (
    SELECT 'CALL.FCC_PSAP_ID -> PSAP_BOUNDARIES.FCC_PSAP_ID' AS COMPARISON,
           COUNT(FCC_ID_NORM) AS NONNULL_CALL_ROWS,
           SUM(CASE WHEN FCC_ID_NORM IN (SELECT ID_VALUE FROM legacy_fcc) THEN 1 ELSE 0 END) AS MATCHED_ROWS
    FROM calls
    UNION ALL
    SELECT 'CALL.PSAP_ID -> PSAP_BOUNDARIES.NENA_ID',
           COUNT(PSAP_ID_NORM),
           SUM(CASE WHEN PSAP_ID_NORM IN (SELECT ID_VALUE FROM legacy_nena) THEN 1 ELSE 0 END)
    FROM calls
    UNION ALL
    SELECT 'CALL.FCC_PSAP_ID -> PSAP_BOUNDARIES_FCC.FCC_PSAP_ID',
           COUNT(FCC_ID_NORM),
           SUM(CASE WHEN FCC_ID_NORM IN (SELECT ID_VALUE FROM fcc_table_id) THEN 1 ELSE 0 END)
    FROM calls
    UNION ALL
    SELECT 'CALL.FCC_PSAP_ID -> BOUNDARIES_FCC JSON FCC_ID',
           COUNT(FCC_ID_NORM),
           SUM(CASE WHEN FCC_ID_NORM IN (SELECT ID_VALUE FROM fcc_json_id) THEN 1 ELSE 0 END)
    FROM calls
    UNION ALL
    SELECT 'CALL.PSAP_NAME -> BOUNDARIES_FCC JSON PSAP_NAME',
           COUNT(PSAP_NAME_NORM),
           SUM(CASE WHEN PSAP_NAME_NORM IN (SELECT ID_VALUE FROM fcc_json_name) THEN 1 ELSE 0 END)
    FROM calls
)
SELECT
    COMPARISON,
    NONNULL_CALL_ROWS,
    MATCHED_ROWS,
    NONNULL_CALL_ROWS - MATCHED_ROWS AS UNMATCHED_ROWS,
    ROUND(100 * MATCHED_ROWS / NULLIF(NONNULL_CALL_ROWS, 0), 2) AS MATCH_RATE_PCT
FROM results
ORDER BY MATCH_RATE_PCT DESC NULLS LAST;

SPOOL OFF
SET MARKUP CSV OFF

PROMPT Mapping check finished.
PROMPT Output: psap_id_mapping_summary.csv

EXIT SUCCESS
